//utils file
export const menuItems = {
    Fan: [
      'Board games revival',
      'Comedy trends',
      'Amusement parks',
      'Escape rooms',
      'Street performances',
      'Online challenges',
      'Festivals impact',
      'Crafting movement',
      'Social gaming',
      'Virtual reality',
    ],
    Education: [
      'Gamified Learning',
      'Education Systems',
      'Bilingual Benefits',
      'Standardized Testing',
      'Arts in Schools',
      'Tech Bootcamp',
      'HomeoSchooling Dynamics',
      'Mentorship Importance',
      'Education equity',
      'Mobile learning',
    ],
    Sports: [
      'Sport Medicine',
      'Team socialogy',
      'Olympic economics',
      'Gender Parity',
      'Fandom Psychology',
      'Extreme sports',
      'Sports business',
      'Youth athletics',
      'Data Analytics',
      'Doping ethics',
    ],
    News: [
      'Citizen Journalism',
      'Whistleblower influnce',
      'Fake news',
      'Print media servival',
      'Social media news',
      'Cybersecurity news',
      'Democratic media',
      'News Deserts',
      'News economics',
      'Broadcast evolution',
    ],
    Investment: [
      'Robo Advising',
      'Geopolitical impact',
      'Index Funds',
      'Real Estate Trends',
      'Startup investing',
      'Social trading',
      'Tax Strategies',
      'Emerging markets',
      'Financial literacy',
      'Pension futures',
    ],
    Fact: [
      'Animal Addities',
      'Everday Science',
      'Historical obscurites',
      'Sceince myths',
      'Human body facts',
      'Oceanic discoveries',
      'Space exploration',
      'Ancient Tech',
      'Worl lawas',
      'Bizzare News',
    ],
  };